# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/clk_800MHz/clk_800MHz.xci
# IP: The module: 'clk_800MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/clk_800MHz/clk_800MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_800MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/clk_800MHz/clk_800MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_800MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/clk_800MHz/clk_800MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_800MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/clk_800MHz/clk_800MHz.xci
# IP: The module: 'clk_800MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/clk_800MHz/clk_800MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_800MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/clk_800MHz/clk_800MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_800MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/clk_800MHz/clk_800MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_800MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
