# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/Users/thkim/Arty_S7/Sequencer/v3_03/v3_03.srcs/sources_1/ip/fifo_generator_bram_64x1024/fifo_generator_bram_64x1024.xci
# IP: The module: 'fifo_generator_bram_64x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_03/v3_03.srcs/sources_1/ip/fifo_generator_bram_64x1024/fifo_generator_bram_64x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_bram_64x1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_03/v3_03.srcs/sources_1/ip/fifo_generator_bram_64x1024/fifo_generator_bram_64x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_bram_64x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: o:/Users/thkim/Arty_S7/Sequencer/v3_03/v3_03.srcs/sources_1/ip/fifo_generator_bram_64x1024/fifo_generator_bram_64x1024.xci
# IP: The module: 'fifo_generator_bram_64x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_03/v3_03.srcs/sources_1/ip/fifo_generator_bram_64x1024/fifo_generator_bram_64x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_bram_64x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_03/v3_03.srcs/sources_1/ip/fifo_generator_bram_64x1024/fifo_generator_bram_64x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_bram_64x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
