# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Jeonghyun/Lab/TaehyunKim/DDS/AD9910/JHPARK/JeonghyunPark/AD9910_CODE-AD9910V1_1/Verilog17/AD9910_V2/AD9910_V2.srcs/sources_1/ip/CLK62_5MHZGen_1/CLK62_5MHZGen.xci
# IP: The module: 'CLK62_5MHZGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Jeonghyun/Lab/TaehyunKim/DDS/AD9910/JHPARK/JeonghyunPark/AD9910_CODE-AD9910V1_1/Verilog17/AD9910_V2/AD9910_V2.srcs/sources_1/ip/CLK62_5MHZGen_1/CLK62_5MHZGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK62_5MHZGen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Jeonghyun/Lab/TaehyunKim/DDS/AD9910/JHPARK/JeonghyunPark/AD9910_CODE-AD9910V1_1/Verilog17/AD9910_V2/AD9910_V2.srcs/sources_1/ip/CLK62_5MHZGen_1/CLK62_5MHZGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK62_5MHZGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Jeonghyun/Lab/TaehyunKim/DDS/AD9910/JHPARK/JeonghyunPark/AD9910_CODE-AD9910V1_1/Verilog17/AD9910_V2/AD9910_V2.srcs/sources_1/ip/CLK62_5MHZGen_1/CLK62_5MHZGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK62_5MHZGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Jeonghyun/Lab/TaehyunKim/DDS/AD9910/JHPARK/JeonghyunPark/AD9910_CODE-AD9910V1_1/Verilog17/AD9910_V2/AD9910_V2.srcs/sources_1/ip/CLK62_5MHZGen_1/CLK62_5MHZGen.xci
# IP: The module: 'CLK62_5MHZGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Jeonghyun/Lab/TaehyunKim/DDS/AD9910/JHPARK/JeonghyunPark/AD9910_CODE-AD9910V1_1/Verilog17/AD9910_V2/AD9910_V2.srcs/sources_1/ip/CLK62_5MHZGen_1/CLK62_5MHZGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK62_5MHZGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Jeonghyun/Lab/TaehyunKim/DDS/AD9910/JHPARK/JeonghyunPark/AD9910_CODE-AD9910V1_1/Verilog17/AD9910_V2/AD9910_V2.srcs/sources_1/ip/CLK62_5MHZGen_1/CLK62_5MHZGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK62_5MHZGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Jeonghyun/Lab/TaehyunKim/DDS/AD9910/JHPARK/JeonghyunPark/AD9910_CODE-AD9910V1_1/Verilog17/AD9910_V2/AD9910_V2.srcs/sources_1/ip/CLK62_5MHZGen_1/CLK62_5MHZGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK62_5MHZGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
