# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/c_counter_binary_16bits/c_counter_binary_16bits.xci
# IP: The module: 'c_counter_binary_16bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/c_counter_binary_16bits/c_counter_binary_16bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_16bits'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/c_counter_binary_16bits/c_counter_binary_16bits.xci
# IP: The module: 'c_counter_binary_16bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/Users/thkim/Arty_S7/Sequencer/v3_05/v3_05.srcs/sources_1/ip/c_counter_binary_16bits/c_counter_binary_16bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_16bits'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
