webtalk_init -webtalk_dir C:/M-Labs/GIT/AD9910_CODE/Verilog17/AD9912_DAC8734/v1_01/v1_01.sim/sim_1/behav/xsim/xsim.dir/testbench_main_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Aug  9 21:03:04 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "329b2b2f-b8c3-4da2-9559-7ae3521673ef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d54dfa7969894540b3406bd82e0ba90c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "51" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "20 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "37.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17264_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3703020292 -regid "" -xml C:/M-Labs/GIT/AD9910_CODE/Verilog17/AD9912_DAC8734/v1_01/v1_01.sim/sim_1/behav/xsim/xsim.dir/testbench_main_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/M-Labs/GIT/AD9910_CODE/Verilog17/AD9912_DAC8734/v1_01/v1_01.sim/sim_1/behav/xsim/xsim.dir/testbench_main_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/M-Labs/GIT/AD9910_CODE/Verilog17/AD9912_DAC8734/v1_01/v1_01.sim/sim_1/behav/xsim/xsim.dir/testbench_main_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
